language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install pipenv
- pipenv install --dev
script:
- pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: lxy1HY2MWDwXta/Do4EXQtLf+z4cEP0KARSkYr08AUM6itQ4CzNT+4ewC9VvmQTtdafnp1HRSOkChOTNAhsF1kKuUaNOrhMEHrc8uwQEb/RfzBulcPOROtSZ5ebN/pzJ3QC/ubKVlTXT2SZujsCFD+mpOZfRDK+01Z+33hiGje6aX5ZNPd8gI7Z+UpjybZadSh7qiATgC6n+2veLfrmdbRGL8fSnhC/vUTHqQN+hL/Qo27ZOrE2lZK8HF4HEO0/4ZmThEEzViFmXYeBJViFjJRlL1WlLsvzZudLFFSXEatkUcG8yh35NFzX0Uz1A8nb1bvDYGutkHJ64Nwq2QraT9MAx1RDzE5JjQA2n5cUpQmVI6pfIIXbOAOXz9FJyOhSq8kXg1aoxdiUJFayNl4JPhQPRDNdeQ+VIvfOnEoVzTWLvJLhv1h3VZTvlY3qUJ8OXBl06M3bGF9QdAhdrN6/pp8SdHrsDRoJKV1rtgzR+8CvqLLQ95xhzJBBvnDtKXOKGakKduRFC1H94Dx0gYW6G+a+A9SpzcSJSM0aaRRsS6mcPDGrRKhM7C6NIw5sWh4ngmyxAY5vbXtfChPDW/vGkmKmdqjKJ5vCIjO/WGRSA9uxEYn4kmo3hVdTmaq0lOR9tkpVzfS0gR8OQo8r4wJLPr+/ANlMWJ+AzKcuMfOfMvwY=
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
