language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install pipenv
- pipenv install --dev
script:
- pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: CG7SaqvlNaBVOnNYMjhBMGMgduQz28q3GzzSBZiJIhxXDpyLVVrhGoW7hM0CMph1eCnVcgEMBBU1YrHOXl4zgSFgNOH4EBpV1pMXxY509vn0SOeeQizk8mEv2S6mPfpBY0tlMEEmsE3CvFHqYl/5EO+1hAsvr2253dttzU8xwhPK+fUN+CSBh5SRiDPNv0/cP1suYscZI8vfb5zdTPkDReY9IwMkv3n+pGuv2B9dkbzDLEIjXC3KnVQomhoZPHFmKtnM6PjY0oNhgSi59N2eCEchzrCP9SLN4qtNoHsp9HT2CzufyrkUUhCYhVWoGvbYU/KoWPo92lCvVHETn40Md0UOxnn4S0HbBdRN384cjf0ymn/DajXLbWWzk0RZAXbV682wGA74pqfLnFw/Wk1uBj/dsDaWzjsdftYmmxYqjaVafqRc33paZdnPMzA2C5c2tUqQ03WSd8iK4dgwV6A58mSwN/AFPRaA3pJMa/W7jRIIgdTnxP867eJhrJcZFpGb0AwSXwNaehLMrL6mwCDQ4ubwSZ20Ei0fa/DsydwRUQ+xGFu2CNYD+EWbi+0LEKWBkb3QW7XRTNSqtrpbtA1LCkKVBPjE/NdtKlGeQjlFkF/RJStKF2We6Duufo1ezhUN6KY05PfnKXXUKiEQEKT5SmptIlWP/6mERJvfki9rPtY=
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
  distributions: sdist bdist_wheel
